function RecentActivity({ predictions }) {

    const recentPredictions = predictions.slice(0, 5);

    return (

        <div
            style={{
                background: "#FFFFFF",
                marginTop: 35,
                borderRadius: 22,
                padding: 30,
                border: "1px solid #E5E7EB",
                boxShadow: "0 8px 24px rgba(15,23,42,.08)"
            }}
        >

            <div
                style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    marginBottom: 25
                }}
            >

                <div>

                    <h2
                        style={{
                            margin: 0,
                            fontSize: 28,
                            color: "#111827"
                        }}
                    >
                        Recent Activity
                    </h2>

                    <p
                        style={{
                            marginTop: 8,
                            color: "#64748B",
                            fontSize: 15
                        }}
                    >
                        Latest machine predictions generated by the AI model.
                    </p>

                </div>

                <div
                    style={{
                        background: "#EFF6FF",
                        color: "#2563EB",
                        padding: "10px 18px",
                        borderRadius: 30,
                        fontWeight: 700
                    }}
                >
                    {recentPredictions.length} Records
                </div>

            </div>

            {

                recentPredictions.length === 0 ?

                    (

                        <div
                            style={{
                                padding: 40,
                                textAlign: "center",
                                color: "#64748B"
                            }}
                        >
                            No recent predictions available.
                        </div>

                    )

                    :

                    recentPredictions.map(item => {

                        const healthy =
                            item.prediction === "Machine Healthy";

                        return (

                            <div
                                key={item.id}
                                style={{
                                    display: "flex",
                                    justifyContent: "space-between",
                                    alignItems: "center",
                                    padding: "18px 0",
                                    borderBottom: "1px solid #E5E7EB"
                                }}
                            >

                                <div
                                    style={{
                                        display: "flex",
                                        alignItems: "center",
                                        gap: 18
                                    }}
                                >

                                    <div
                                        style={{
                                            width: 14,
                                            height: 14,
                                            borderRadius: "50%",
                                            background:
                                                healthy
                                                    ? "#16A34A"
                                                    : "#DC2626"
                                        }}
                                    />

                                    <div>

                                        <div
                                            style={{
                                                fontWeight: 700,
                                                color: "#111827",
                                                marginBottom: 6
                                            }}
                                        >
                                            {item.prediction}
                                        </div>

                                        <div
                                            style={{
                                                color: "#64748B",
                                                fontSize: 14
                                            }}
                                        >
                                            Confidence: {item.confidence}%
                                        </div>

                                    </div>

                                </div>

                                <div
                                    style={{
                                        textAlign: "right"
                                    }}
                                >

                                    <div
                                        style={{
                                            background:
                                                healthy
                                                    ? "#DCFCE7"
                                                    : "#FEE2E2",
                                            color:
                                                healthy
                                                    ? "#15803D"
                                                    : "#B91C1C",
                                            padding: "8px 16px",
                                            borderRadius: 30,
                                            fontWeight: 700,
                                            display: "inline-block",
                                            marginBottom: 8
                                        }}
                                    >
                                        {healthy ? "Healthy" : "Failure"}
                                    </div>

                                    <div
                                        style={{
                                            color: "#64748B",
                                            fontSize: 13
                                        }}
                                    >
                                        {new Date(
                                            item.created_at
                                        ).toLocaleString()}
                                    </div>

                                </div>

                            </div>

                        );

                    })

            }

        </div>

    );

}

export default RecentActivity;