import { useEffect, useState } from "react";
import { getPredictions } from "../utils/api";

function PredictionHistory() {

    const [predictions, setPredictions] = useState([]);
    const [search, setSearch] = useState("");

    useEffect(() => {
        loadPredictions();
    }, []);

    async function loadPredictions() {

        try {

            const data = await getPredictions();
            setPredictions(data.reverse());

        } catch (err) {

            console.log(err);

        }

    }

    const healthyCount = predictions.filter(
        p => p.prediction === "Machine Healthy"
    ).length;

    const failureCount = predictions.filter(
        p => p.prediction === "Machine Failure Predicted"
    ).length;

    const avgConfidence =
        predictions.length > 0
            ? (
                predictions.reduce(
                    (sum, p) => sum + Number(p.confidence),
                    0
                ) / predictions.length
            ).toFixed(2)
            : "0.00";

    const filtered = predictions.filter(p =>
        p.prediction.toLowerCase().includes(search.toLowerCase())
    );

    return (

        <div
            style={{
                padding: "35px",
                background: "#eef2f7",
                minHeight: "100vh"
            }}
        >

            {/* Header */}

            {/* Header */}

            <div
                style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "flex-start",
                    flexWrap: "wrap",
                    gap: "20px",
                    marginBottom: "35px"
                }}
            >

                <div>

                    <p
                        style={{
                            color: "#2563EB",
                            fontWeight: "700",
                            fontSize: "14px",
                            letterSpacing: "1px",
                            textTransform: "uppercase",
                            marginBottom: "8px"
                        }}
                    >
                        Prediction Monitoring
                    </p>

                    <h1
                        style={{
                            fontSize: "38px",
                            fontWeight: "700",
                            color: "#111827",
                            margin: 0
                        }}
                    >
                        Prediction History
                    </h1>

                    <p
                        style={{
                            marginTop: "12px",
                            color: "#6B7280",
                            fontSize: "16px",
                            maxWidth: "650px",
                            lineHeight: "26px"
                        }}
                    >
                        View and analyze all machine health predictions generated by the
                        AI predictive maintenance engine. Search historical records,
                        monitor confidence scores and export reports.
                    </p>

                </div>

                <div
                    style={{
                        display: "flex",
                        gap: "15px"
                    }}
                >

                    <button style={secondaryButton}>
                        Export PDF
                    </button>

                    <button style={primaryButton}>
                        Export CSV
                    </button>

                </div>

            </div>

            {/* KPI Cards */}

            <div
                style={{
                    display: "grid",
                    gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
                    gap: "20px",
                    marginBottom: "30px"
                }}
            >

                <SummaryCard
                    title="Total Predictions"
                    value={predictions.length}
                    color="#2563EB"
                />

                <SummaryCard
                    title="Healthy Machines"
                    value={healthyCount}
                    color="#16A34A"
                />

                <SummaryCard
                    title="Failure Predictions"
                    value={failureCount}
                    color="#DC2626"
                />

                <SummaryCard
                    title="Average Confidence"
                    value={`${avgConfidence}%`}
                    color="#7C3AED"
                />

            </div>

            {/* Search */}

            <div
                style={{
                    background: "#fff",
                    borderRadius: "16px",
                    padding: "20px",
                    marginBottom: "30px",
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    gap: "20px",
                    flexWrap: "wrap",
                    boxShadow: "0 8px 24px rgba(15,23,42,.06)"
                }}
            >

                <input
                    type="text"
                    placeholder="Search by prediction..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    style={{
                        flex: 1,
                        minWidth: "320px",
                        padding: "14px 18px",
                        borderRadius: "10px",
                        border: "1px solid #d1d5db",
                        fontSize: "15px",
                        outline: "none"
                    }}
                />

                <div
                    style={{
                        color: "#6B7280",
                        fontWeight: "600"
                    }}
                >
                    Showing {filtered.length} of {predictions.length} records
                </div>

            </div>

            {/* Table */}

            <div
                style={{
                    overflowX: "auto",
                    background: "#fff",
                    borderRadius: "20px",
                    boxShadow: "0 15px 40px rgba(15,23,42,.08)"
                }}
            >

                <table
                    style={{
                        width: "100%",
                        borderCollapse: "collapse"
                    }}
                >

                    <thead>

                        <tr
                            style={{
                                background: "#1E3A8A",
                                color: "#fff"
                            }}
                        >

                            <th style={headStyle}>ID</th>
                            <th style={headStyle}>Prediction</th>
                            <th style={headStyle}>Confidence</th>
                            <th style={headStyle}>Timestamp</th>
                            <th style={headStyle}>Status</th>

                        </tr>

                    </thead>

                    <tbody>

                        {filtered.map((p, index) => (

                            <tr
                                key={p.id}
                                style={{
                                    background:
                                        index % 2 === 0
                                            ? "#ffffff"
                                            : "#f8fafc"
                                }}
                            >

                                <td style={cellStyle}>{p.id}</td>

                                <td
                                    style={{
                                        ...cellStyle,
                                        fontWeight: "600"
                                    }}
                                >
                                    {p.prediction}
                                </td>

                                <td style={cellStyle}>

                                    <span
                                        style={{
                                            background: "#DBEAFE",
                                            color: "#1D4ED8",
                                            padding: "6px 12px",
                                            borderRadius: "20px",
                                            fontWeight: "600"
                                        }}
                                    >
                                        {p.confidence}%
                                    </span>

                                </td>

                                <td style={cellStyle}>
                                    {new Date(p.created_at).toLocaleString()}
                                </td>

                                <td style={cellStyle}>

                                    <span
                                        style={{
                                            background:
                                                p.prediction === "Machine Healthy"
                                                    ? "#DCFCE7"
                                                    : "#FEE2E2",

                                            color:
                                                p.prediction === "Machine Healthy"
                                                    ? "#15803D"
                                                    : "#B91C1C",

                                            padding: "7px 14px",

                                            borderRadius: "20px",

                                            fontWeight: "600"
                                        }}
                                    >
                                        {p.prediction === "Machine Healthy"
                                            ? "Healthy"
                                            : "Failure"}
                                    </span>

                                </td>

                            </tr>

                        ))}

                    </tbody>

                </table>

            </div>

        </div>

    );

}

function SummaryCard({ title, value, color }) {

    return (

        <div
            style={{
                background: "#fff",
                borderRadius: "18px",
                padding: "22px",
                borderTop: `5px solid ${color}`,
                boxShadow: "0 8px 20px rgba(15,23,42,0.08)"
            }}
        >

            <p
                style={{
                    color: "#6B7280",
                    marginBottom: "10px"
                }}
            >
                {title}
            </p>

            <h2
                style={{
                    color,
                    fontSize: "34px",
                    margin: 0
                }}
            >
                {value}
            </h2>

        </div>

    );

}

const headStyle = {
    padding: "18px",
    fontWeight: "600",
    fontSize: "15px"
};

const cellStyle = {
    padding: "18px",
    textAlign: "center",
    borderBottom: "1px solid #e5e7eb"
};

const secondaryButton = {
    padding: "12px 20px",
    background: "#fff",
    border: "1px solid #d1d5db",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600"
};

const primaryButton = {
    padding: "12px 20px",
    background: "#2563EB",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600"
};

export default PredictionHistory;